// <auto-generated />
namespace TransportationManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class shipment_tracking_identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shipment_tracking_identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201512102042284_shipment_tracking_identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
